groups:
- name: telegram-alert
  rules:

  - alert: service_down
    expr: up{job="oncall_oncall-web_1"} == 0
    for: 5s
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 30 seconds."
