groups:
- name: telegram-alert
  rules:

  - alert: service_down
    expr: up{job="oncall_web"} == 0
    for: 10s
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 10 seconds."

  - alert: service_dns_slowed_down
    expr: probe_dns_lookup_time_seconds{job='blackbox-http'} > 0.001
    for: 5s
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} has high dns_lookup_time latency"
      description: "DNS lookup in {{ $labels.instance }} of job {{ $labels.job }} has been slowed down(>0.001 sec) for more than 5 seconds."


  - alert: network_drop
    expr: node_network_receive_drop_total{job='node-exporter'} > 0
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} has bad network"
      description: "Network recive drop exists in {{ $labels.instance }} of job {{ $labels.job }} ."
