version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - iris
  oncall-web:
    build: .
    hostname: oncall
    ports:
      - "8080:8080"
      - "8585:8585"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
    volumes:
      - ./configs/config.docker.yaml:/home/oncall/config/config.yaml
    networks:
      - iris
  
  oncall-mysql:
    hostname: oncall-mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - iris

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"

networks:
  iris:
    name: iris
