version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alermanager/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
    networks:
      - iris
  
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - --config.file=/etc/alertmanager/alermanager.yml
      - --storage.path=/etc/alertmanager/

  oncall-web:
    build: .
    hostname: oncall
    ports:
      - "8080:8080"
      - "8585:8585"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
    volumes:
      - ./configs/config.docker.yaml:/home/oncall/config/config.yaml
    networks:
      - iris
  
  oncall-mysql:
    hostname: oncall-mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - iris

  my_textfile_collector:
    build: ./textfile_collectors/.
    volumes:
      - ./textfile_collectors/metrics:/metrics
    networks:
      - iris

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    command:
      --collector.disable-defaults
      --collector.diskstats
      --collector.cpu
      --collector.filesystem
      --collector.meminfo
      --collector.netdev
      --collector.textfile
      --collector.textfile.directory=./metrics/
    volumes:
      - ./textfile_collectors/metrics:/metrics
    networks:
      - iris

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"
    command:
      --config.file=/etc/blackbox/blackbox.yml
    volumes:
      - ./configs/blackbox.yml:/etc/blackbox/blackbox.yml
    networks:
      - iris


networks:
  iris:
    name: iris
