global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'oncall_web'
    static_configs:
      - targets: ['oncall_oncall-web_1:8585']
    scrape_interval: 10s
    

