global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'oncall_web'
    static_configs:
      - targets: ['oncall_oncall-web_1:8585']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['oncall_node-exporter:9100']
