global:
  scrape_interval:     10s

scrape_configs:
  - job_name: 'oncall_web'
    static_configs:
      - targets: ['oncall_oncall-web_1:8585']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['oncall_node-exporter_1:9100']
  
  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module:
      - http_2xx
    relabel_configs:
    - source_labels:
      - __address__
      target_label: __param_target
    - source_labels:
      - __param_target
      target_label: instance
    - replacement: oncall_blackbox-exporter_1:9115
      target_label: __address__
    static_configs:
    - targets:
      - 'oncall_oncall-web_1:8080'

  - job_name: "blackbox-icmp"
    metrics_path: "/probe"
    params:
      module: [ "icmp" ]
    relabel_configs:
      - source_labels: [ "__address__" ]
        target_label: "__param_target"
      - source_labels: [ "__param_target" ]
        target_label: "instance"
      - target_label: "__address__"
        replacement: "oncall_blackbox-exporter_1:9115"
    static_configs:
      - targets:
        - 'oncall_oncall-web_1:8080'

  - job_name: "blackbox-tcp"
    metrics_path: "/probe"
    params:
      module: [ "tcp_connect" ]
    relabel_configs:
      - source_labels: [ "__address__" ]
        target_label: "__param_target"
      - source_labels: [ "__param_target" ]
        target_label: "instance"
      - target_label: "__address__"
        replacement: "oncall_blackbox-exporter_1:9115"
    static_configs:
      - targets:
        - 'oncall_oncall-web_1:8080'